services:
  discovery-server:
    container_name: discovery-server
    image: discovery-server-service
    ports:
      - "17601:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761"]

  api-gateway:
    container_name: api-gateway
    image: api-gateway-service
    expose:
      - "8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      offer-service:
        condition: service_healthy
      flight-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api-gateway:8080/offers"]

  client:
    container_name: client-service
    image: client-service
    ports:
      - "17600:10000"
    depends_on:
      api-gateway:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      API_GATEWAY_URI: http://localhost:8080

  offer-service:
    container_name: offer-service
    image: hotel-service
    expose:
      - "8081"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://172.17.0.1:27017/hotels
      RABBITMQ_HOST_ADDRESS: localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://offer-service:8081/offers"]
  
  flight-service:
    container_name: flight-service
    image: flight-service
    expose:
      - "8082"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://172.17.0.1:27017/flights
      RABBITMQ_HOST_ADDRESS: localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://flight-service:8082/flights"]

  payment-service:
    container_name: payment-service
    image: payment-service
    expose:
      - "8083"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://172.17.0.1:27017/bills
      RABBITMQ_HOST_ADDRESS: localhost

  reservation-master-service:
    container_name: reservation-master-service
    image: reservation-master-service
    expose:
      - "8084"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://172.17.0.1:27017/reservations_master
      RABBITMQ_HOST_ADDRESS: localhost
  
  reservation-service:
    container_name: reservation-service
    image: reservation-service
    expose:
      - "8085"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://172.17.0.1:27017/reservations
      RABBITMQ_HOST_ADDRESS: localhost

  tour-operator:
    container_name: tour-operator
    image: tour-operator
    expose:
      - ":8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      RABBITMQ_HOST_ADDRESS: localhost

  travel-agency:
    container_name: travel-agency
    image: travel-agency
    expose:
      - "8087"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://172.17.0.1:27017/travel_agency
      RABBITMQ_HOST_ADDRESS: localhost

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - "5672"
    ports:
      - "17602:15672"
    depends_on:
      discovery-server:
        condition: service_healthy