server:
  port: 8082
spring:
  application:
    name: flight-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/flights
      username: root
      password: student
  cloud:
    stream:
      function:
        definition: createFlightHandle;deleteFlightHandle;updateFlightHandle
      bindings:
        createFlightHandle-in-0:
          destination: cqrs_flights_create
          group: 0
        deleteFlightHandle-in-0:
          destination: cqrs_flights_delete
          group: 0
        updateFlightHandle-in-0:
          destination: cqrs_flights_update
          group: 0

  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/