server:
  port: 8085
spring:
  application:
    name: travel-agency-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
  cloud:
    stream:
      function:
        definition: blockResources; unblockResources; createFlightCQRSHandle; createOfferCQRSHandle; deleteFlightCQRSHandle; deleteOfferCQRSHandle; updateFlightCQRSHandle; updateOfferCQRSHandle; cancelReservation; modifyOffer; modifyFlight
      bindings:
        blockResources-in-0:
          destination: sage_block_resources
          group: 0
        blockResources-out-0:
          destination: saga_reservation_succesful
          group: 0
        unblockResources-in-0:
          destination: saga_unblock_resources
          group: 0
        unblockResources-out-0:
          destination: saga_cancel_reservation
          group: 0
        cancelReservation-out-0:
          destination: saga_cancel_reservation
          group: 0
        createFlightCQRSHandle-out-0:
          destination: cqrs_flights_create
          group: 0
        createOfferCQRSHandle-out-0:
          destination: cqrs_offers_create
          group: 0
        deleteFlightCQRSHandle-out-0:
          destination: cqrs_flights_delete
          group: 0
        deleteOfferCQRSHandle-out-0:
          destination: cqrs_offers_delete
          group: 0
        updateFlightCQRSHandle-out-0:
          destination: cqrs_flights_update
          group: 0
        updateOfferCQRSHandle-out-0:
          destination: cqrs_offers_update
          group: 0
        modifyOffer-in-0:
          destination: to_offer_modifications
          group: 0
        modifyFlight-in-0:
          destination: to_flight_modifications
          group: 0

  rabbitmq:
    username: guest
    password: guest
    host: ${RABBITMQ_HOST_ADDRESS}
    port: 5672

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/