server:
  port: 8085
spring:
  application:
    name: travel-agency-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/travel_agency
      username: root
      password: student
  cloud:
    stream:
      function:
        definition: blockResources; unblockResources; createFlightCQRSHandle; createOfferCQRSHandle; deleteFlightCQRSHandle; deleteOfferCQRSHandle; updateFlightCQRSHandle; updateOfferCQRSHandle; cancelReservation
      bindings:
        blockResources-in-0:
          destination: sage_block_resources
          group: 0
        blockResources-out-0:
          destination: saga_reservation_succesful
          group: 0
        unblockResources-in-0:
          destination: saga_unblock_resources
          group: 0
        unblockResources-out-0:
          destination: saga_cancel_reservation
          group: 0
        cancelReservation-out-0:
          destination: saga_cancel_reservation
          group: 0
        createFlightCQRSHandle-out-0:
          destination: cqrs_flights_create
          group: 0
        createOfferCQRSHandle-out-0:
          destination: cqrs_offers_create
          group: 0
        deleteFlightCQRSHandle-out-0:
          destination: cqrs_flights_delete
          group: 0
        deleteOfferCQRSHandle-out-0:
          destination: cqrs_offers_delete
          group: 0
        updateFlightCQRSHandle-out-0:
          destination: cqrs_flights_update
          group: 0
        updateOfferCQRSHandle-out-0:
          destination: cqrs_offers_update
          group: 0

  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/