server:
  port: 8086
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/travel_agency
#  cloud:
#    stream:
#      function:
#        definition: createOfferHandle;deleteOfferHandle;updateOfferHandle
#      bindings:
#        createFlightHandle-in-0:
#          destination: cqrs_offers_create
#        deleteFlightHandle-in-0:
#          destination: cqrs_offers_delete
#        updateFlightHandle-in-0:
#          destination: cqrs_offers_update
#
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    port: 5672