server:
  port: 0
spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/hotels
  cloud:
    stream:
      function:
        definition: blockResources; unblockResources
      bindings:
        blockResources-in-0:
          destination: sage_make_reservation
        blockResources-out-0:
          destination: saga_require_payment
#        receiveReservation2-in-0:
#          destination: saga_require_payment2
#        receiveReservation2-out-0:
#          destination: saga_require_payment
        unblockResources-in-0:
          destination: saga_unblock_resources
        unblockResources-out-0:
          destination: saga_remove_reservation
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672