server:
  port: 8085
spring:
  application:
    name: travel-agency-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/travel_agency
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/