server:
  port: 0
spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/hotels
  cloud:
    stream:
      function:
        definition: receiveReservation
      bindings:
        receiveReservation-in-0:
          destination: sage_make_reservation
        receiveReservation-out-0:
          destination: saga_require_payment


  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672