server:
  port: 8084
spring:
  application:
    name: reservation-master-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
  cloud:
    stream:
      rabbit:
        bindings:
          requireValidation-out-0:
            producer:
              autoBindDlq: true
              ttl: 20000
              deadLetterExchange: delay-topic
              deadLetterQueueName: delay-topic.test
              deadLetterExchangeType: topic
      function:
        definition: removeReservation; createReservationCQRSHandle; deleteReservationCQRSHandle; updateReservationCQRSHandle; finaliseReservation; makeReservation; confirmReservation; requireValidation; confirmReservationId; requestRefund; receivePayment
      bindings:
        makeReservation-in-0:
          destination: sage_make_reservation
          group: 0
        makeReservation-out-0:
          destination: sage_block_resources
          group: 0
        removeReservation-in-0:
          destination: saga_cancel_reservation
          group: 0
        createReservationCQRSHandle-out-0:
          destination: cqrs_reservations_create
          group: 0
        deleteReservationCQRSHandle-out-0:
          destination: cqrs_reservations_delete
          group: 0
        updateReservationCQRSHandle-out-0:
          destination: cqrs_reservations_update
          group: 0
        requireValidation-out-0:
          destination: temp
          producer:
            requiredGroups: test
        finaliseReservation-out-0:
          destination: to_notif_purchases
          group: 0
        confirmReservation-in-0:
          destination: saga_reservation_succesful
          group: 0
        confirmReservationId-out-0:
          destination: saga_reservationId_update
          group: 0
        requestRefund-out-0:
          destination: saga_refunds
          group: 0
        receivePayment-in-0:
          destination: saga_paid_reservation
          group: 0

  rabbitmq:
    username: guest
    password: guest
    host: ${RABBITMQ_HOST_ADDRESS}
    port: 5672
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/