server:
  port: 8087
spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bills
      username: root
      password: student
  cloud:
    stream:
      function:
        definition: makeReservation; validatePayment; failTransaction; confirmReservationId; refundPayment; succeedTransaction; notifyClient
      bindings:
        makeReservation-out-0:
          destination: sage_make_reservation
          group: 0
        validatePayment-in-0:
          destination: delay-topic
          group: test
        succeedTransaction-out-0:
          destination: saga_paid_reservation
          group: 0
        failTransaction-out-0:
          destination: saga_unblock_resources
          group: 0
        confirmReservationId-in-0:
          destination: saga_reservationId_update
          group: 0
        refundPayment-in-0:
          destination: saga_refunds
          group: 0
        notifyClient-out-0:
          destination: notify_client
          group: 0

  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/