server:
  port: 8087
spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/