server:
  port: 0
spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/hotels
  cloud:
    stream:
      rabbit:
        bindings:
          processPayment-out-0:
            producer:
              autoBindDlq: true
              ttl: 5000
              deadLetterExchange: delay-topic
              deadLetterQueueName: delay-topic.test
              deadLetterExchangeType: topic

      function:
        definition: processPayment; validatePayment; failTransaction
      bindings:
        processPayment-in-0:
          destination: saga_require_payment
        processPayment-out-0:
          destination: temp
          producer:
            requiredGroups: test
        validatePayment-in-0:
          destination: delay-topic
          group: test
        failTransaction-out-0:
          destination: saga_unblock_resources

  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
