server:
  port: 8900

spring:
  application:
    name: tour-operator
  cloud:
    stream:
      poller:
        fixed-delay: 10000
      function:
        definition: receivePaymentNotif; modifyOffer; modifyFLight
      bindings:
        receivePaymentNotif-in-0:
          destination: to_notif_purchases
          group: 0
        modifyOffer-out-0:
          destination: to_offer_modifications
          group: 0
        modifyFLight-out-0:
          destination: to_flight_modifications
          group: 0

  rabbitmq:
    username: guest
    password: guest
    host: ${RABBITMQ_HOST_ADDRESS}
    port: 5672