server:
  port: 0
spring:
  cloud:
    stream:
      function:
        definition: receivePaymentNotif
      bindings:
        receivePaymentNotif-in-0:
          destination: to_notif_purchases


  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672