server:
  port: 8900
spring:
  application:
    name: tour-operator
  integration:
    poller:
      fixedDelay: 10000
  cloud:
    stream:
      function:
        definition: receivePaymentNotif; modifyOffer; modifyFLight
      bindings:
        receivePaymentNotif-in-0:
          destination: to_notif_purchases
          group: 0
        modifyOffer-out-0:
          destination: to_offer_modifications
          group: 0
        modifyFLight-out-0:
          destination: to_flight_modifications
          group: 0
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672

path-to-offer-ids-file: tour-operator/src/main/java/touroperator/offers_ids.txt
path-to-flight-ids-file: tour-operator/src/main/java/touroperator/flights_ids.txt
