server:
  port: 333
spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/hotels
  cloud:
    stream:
      function:
        definition: createReservationHandle;deleteReservationHandle;updateReservationHandle
      bindings:
        createReservationHandle-in-0:
          destination: cqrs_reservations_create
        deleteReservationHandle-in-0:
          destination: cqrs_reservations_delete
        updateReservationHandle-in-0:
          destination: cqrs_reservations_update


  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672