server:
  port: 8083
spring:
  application:
    name: reservation-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/reservations
  cloud:
    stream:
      function:
        definition: createReservationHandle;deleteReservationHandle;updateReservationHandle
      bindings:
        createReservationHandle-in-0:
          destination: cqrs_reservations_create
        deleteReservationHandle-in-0:
          destination: cqrs_reservations_delete
        updateReservationHandle-in-0:
          destination: cqrs_reservations_update
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/