server:
  port: 8080

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: offer-service
          uri: lb://offer-service
          predicates:
            - Path=/offers,/offers/{offerId},/statistics/offers/rooms,/statistics/offers/hotels
            - Method=GET
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights,/flights/{flightId},/statistics/flights/destinations
            - Method=GET
        - id: reservations-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservations,/reservations/{reservationId}
            - Method=GET
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/makereservation,/pay/{paymentId}/{status},/pay/{status},/pay
            - Method=GET,PUT,POST,OPTIONS

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
    stream:
      function:
        definition: sendNotification
      bindings:
        sendNotification-in-0:
          destination: notify_client
          group: 0

  rabbitmq:
    username: guest
    password: guest
    host: ${RABBITMQ_HOST_ADDRESS}
    port: 5672

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  instance:
    hostname: api_gateway
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
