server:
  port: 8080

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: offer-service
          uri: http://localhost:8081
          predicates:
            - Path=/offers,/offers/{offerId}
        - id: flight-service
          uri: http://localhost:8082
          predicates:
            - Path=/flights,/flights/{flightId}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE