server:
  port: 8080

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: offer-service
          uri: lb://offer-service
          predicates:
            - Path=/offers,/offers/{offerId}
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights,/flights/{flightId}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  instance:
    hostname: api_gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#offer-service:
 # ribbon:
  #  listOfServers: http://offer-service